---
- name: playbook to manage i7
  hosts: local
  gather_facts: no
  become: true
  vars:
    username: kirilche
    path_to_files: /home/{{ username }}/ansible-debian-laptop
    apt_mirror: mirror.mirohost.net
    gcp_sdk_path: /home/{{ username }}
    google_chrome_download_url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    virtualbox_download_url: https://download.virtualbox.org/virtualbox/6.1.12/virtualbox-6.1_6.1.12-139181~Debian~buster_amd64.deb
    # go to https://download.virtualbox.org/virtualbox/6.1.12/ to check for new build
    vscode_download_url: https://go.microsoft.com/fwlink/?LinkID=760868
    # minishift_release: 1.34.2
    # minishift_download_url: https://github.com/minishift/minishift/releases/download/v{{ minishift_release }}/minishift-{{ minishift_release }}-linux-amd64.tgz
    # minishift_path: /home/{{ username }}/.local/bin
    tfenv_download_url: https://github.com/tfutils/tfenv/archive/v2.0.0.tar.gz
    tfenv_path: /home/{{ username }}/.tfenv
  tasks:
  - import_tasks: tasks/01_install_packages.yml
  # # - import_tasks: tasks/gnome_config.yml
  # - import_tasks: tasks/git_config.yml
  # - import_tasks: tasks/02_gcp_sdk.yml
  # - import_tasks: tasks/02_google_chrome.yml
  # - import_tasks: tasks/02_virtualbox.yml
  # - import_tasks: tasks/02_vscode.yml
  # - import_tasks: tasks/03_kubectl_gcloud.yml
  # - import_tasks: tasks/04_minikube_gcloud.yml
  # # - import_tasks: tasks/04_minishift.yml
  # - import_tasks: tasks/05_terraform.yml


