- name: contrib and non-free to /etc/apt/sources.list
  lineinfile:
    backup: yes
    path: /etc/apt/sources.list
    regexp: '^deb http://{{ apt_mirror }}/debian/ buster main'
    line: 'deb http://{{ apt_mirror }}/debian/ buster main contrib non-free'
    state: present

- name: setup Wifi, Net-Tools, Curl, Zip, Git, VLC, SMPlayer
  apt:
    pkg:
      - firmware-iwlwifi
      - net-tools
      - curl
      - zip
      - git
      - vlc
      - smplayer
    
    update_cache: yes
    state: latest