- name: NOsudo block
  block:
  - name: check if kubectl installed
    command: kubectl version --client
    register: kubectl_version
    ignore_errors: yes
    changed_when: no

  - name: install kubectl as gcloud component
    command:
      cmd: gcloud components install kubectl
    when: kubectl_version.rc != 0
  #NOsudo block
  become: no
  