- name: NOsudo block
  block:

  - name: Download 
    get_url:
      url: "{{ minishift_download_url }}"
      dest: files/minishift.tar.gz
      force: no

  - name: check if minishift installed
    command: minishift version
    register: minishift_version
    ignore_errors: yes
    changed_when: no
    
  - name: command not found block 
    block:

    - name: Unarchive
      unarchive:
        src: files/minishift.tar.gz
        dest: "{{ minishift_path }}"
        extra_opts: [--strip-components=1]
      
    - name: add cli to $PATH
      lineinfile:
        path: "/home/{{ username }}/.bashrc"
        line: "export PATH={{ minishift_path }}:$PATH"
        state: present
        insertafter: EOF
    #block command not found    
    when: minishift_version.rc != 0

  #NOsudo block 
  become: no